#!/bin/bash
clear

FILE=docker-compose.yml

docker-compose -f $FILE kill
docker-compose -f $FILE down
docker-compose -f $FILE build
docker-compose -f $FILE up -d nginx
docker-compose -f $FILE up -d fixture
docker-compose -f $FILE up
