version: '2'
services:
    postgres:
        restart: always
        image: postgres:latest
        ports:
            - "5432:5432"

    migration:
        build:
            context: ./web
            dockerfile: Dockerfile_dev
        image: espenfolke/webstarter_migration:dev
        command: bash -c "python manage.py migrate && python manage.py makemigrations && python manage.py migrate"
        env_file: .env_dev
        volumes:
            - ./web:/usr/src/app
        links:
            - postgres
        depends_on:
            - postgres

    fixture:
        build:
            context: ./web
            dockerfile: Dockerfile_dev
        image: espenfolke/webstarter_fixture:dev
        command: bash -c "python manage.py loaddata dashboard/fixtures/rooms.json"
        env_file: .env_dev
        volumes:
            - ./web:/usr/src/app
        links:
            - postgres
            - migration
        depends_on:
            - postgres
            - migration

    web:
        restart: always
        build:
            context: ./web
            dockerfile: Dockerfile_dev
        image: espenfolke/webstarter_web:dev
        expose:
            - "8000"
        links:
            - postgres:postgres
        volumes:
            - ./web:/usr/src/app
            - /usr/src/app/static
        env_file: .env_dev
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - postgres

    nginx:
        restart: always
        build: ./nginx/
        image: espenfolke/webstarter_nginx:dev
        ports:
            - "80:80"
        volumes:
            - /www/static
        volumes_from:
            - web
        links:
            - web:web
